// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: odds_engine.proto
#ifndef GRPC_odds_5fengine_2eproto__INCLUDED
#define GRPC_odds_5fengine_2eproto__INCLUDED

#include "odds_engine.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace odds {

class OddsEngine final {
 public:
  static constexpr char const* service_full_name() {
    return "odds.OddsEngine";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Called by the manager to update match state for a specific game
    virtual ::grpc::Status UpdateMatchState(::grpc::ClientContext* context, const ::odds::MatchStateRequest& request, ::odds::OddsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>> AsyncUpdateMatchState(::grpc::ClientContext* context, const ::odds::MatchStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>>(AsyncUpdateMatchStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>> PrepareAsyncUpdateMatchState(::grpc::ClientContext* context, const ::odds::MatchStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>>(PrepareAsyncUpdateMatchStateRaw(context, request, cq));
    }
    // Called when a user places a bet; updates exposure + recalculates odds
    virtual ::grpc::Status PlaceBet(::grpc::ClientContext* context, const ::odds::BetRequest& request, ::odds::OddsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>> AsyncPlaceBet(::grpc::ClientContext* context, const ::odds::BetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>>(AsyncPlaceBetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>> PrepareAsyncPlaceBet(::grpc::ClientContext* context, const ::odds::BetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>>(PrepareAsyncPlaceBetRaw(context, request, cq));
    }
    // Called to fetch latest odds for any market in any game
    virtual ::grpc::Status GetOdds(::grpc::ClientContext* context, const ::odds::OddsQueryRequest& request, ::odds::OddsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>> AsyncGetOdds(::grpc::ClientContext* context, const ::odds::OddsQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>>(AsyncGetOddsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>> PrepareAsyncGetOdds(::grpc::ClientContext* context, const ::odds::OddsQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>>(PrepareAsyncGetOddsRaw(context, request, cq));
    }
    virtual ::grpc::Status SetInitialOdds(::grpc::ClientContext* context, const ::odds::SetInitialOddsRequest& request, ::odds::Ack* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::Ack>> AsyncSetInitialOdds(::grpc::ClientContext* context, const ::odds::SetInitialOddsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::Ack>>(AsyncSetInitialOddsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::Ack>> PrepareAsyncSetInitialOdds(::grpc::ClientContext* context, const ::odds::SetInitialOddsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::Ack>>(PrepareAsyncSetInitialOddsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Called by the manager to update match state for a specific game
      virtual void UpdateMatchState(::grpc::ClientContext* context, const ::odds::MatchStateRequest* request, ::odds::OddsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateMatchState(::grpc::ClientContext* context, const ::odds::MatchStateRequest* request, ::odds::OddsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Called when a user places a bet; updates exposure + recalculates odds
      virtual void PlaceBet(::grpc::ClientContext* context, const ::odds::BetRequest* request, ::odds::OddsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PlaceBet(::grpc::ClientContext* context, const ::odds::BetRequest* request, ::odds::OddsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // Called to fetch latest odds for any market in any game
      virtual void GetOdds(::grpc::ClientContext* context, const ::odds::OddsQueryRequest* request, ::odds::OddsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetOdds(::grpc::ClientContext* context, const ::odds::OddsQueryRequest* request, ::odds::OddsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SetInitialOdds(::grpc::ClientContext* context, const ::odds::SetInitialOddsRequest* request, ::odds::Ack* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetInitialOdds(::grpc::ClientContext* context, const ::odds::SetInitialOddsRequest* request, ::odds::Ack* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>* AsyncUpdateMatchStateRaw(::grpc::ClientContext* context, const ::odds::MatchStateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>* PrepareAsyncUpdateMatchStateRaw(::grpc::ClientContext* context, const ::odds::MatchStateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>* AsyncPlaceBetRaw(::grpc::ClientContext* context, const ::odds::BetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>* PrepareAsyncPlaceBetRaw(::grpc::ClientContext* context, const ::odds::BetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>* AsyncGetOddsRaw(::grpc::ClientContext* context, const ::odds::OddsQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>* PrepareAsyncGetOddsRaw(::grpc::ClientContext* context, const ::odds::OddsQueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::odds::Ack>* AsyncSetInitialOddsRaw(::grpc::ClientContext* context, const ::odds::SetInitialOddsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::odds::Ack>* PrepareAsyncSetInitialOddsRaw(::grpc::ClientContext* context, const ::odds::SetInitialOddsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status UpdateMatchState(::grpc::ClientContext* context, const ::odds::MatchStateRequest& request, ::odds::OddsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>> AsyncUpdateMatchState(::grpc::ClientContext* context, const ::odds::MatchStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>>(AsyncUpdateMatchStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>> PrepareAsyncUpdateMatchState(::grpc::ClientContext* context, const ::odds::MatchStateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>>(PrepareAsyncUpdateMatchStateRaw(context, request, cq));
    }
    ::grpc::Status PlaceBet(::grpc::ClientContext* context, const ::odds::BetRequest& request, ::odds::OddsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>> AsyncPlaceBet(::grpc::ClientContext* context, const ::odds::BetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>>(AsyncPlaceBetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>> PrepareAsyncPlaceBet(::grpc::ClientContext* context, const ::odds::BetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>>(PrepareAsyncPlaceBetRaw(context, request, cq));
    }
    ::grpc::Status GetOdds(::grpc::ClientContext* context, const ::odds::OddsQueryRequest& request, ::odds::OddsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>> AsyncGetOdds(::grpc::ClientContext* context, const ::odds::OddsQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>>(AsyncGetOddsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>> PrepareAsyncGetOdds(::grpc::ClientContext* context, const ::odds::OddsQueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>>(PrepareAsyncGetOddsRaw(context, request, cq));
    }
    ::grpc::Status SetInitialOdds(::grpc::ClientContext* context, const ::odds::SetInitialOddsRequest& request, ::odds::Ack* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::Ack>> AsyncSetInitialOdds(::grpc::ClientContext* context, const ::odds::SetInitialOddsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::Ack>>(AsyncSetInitialOddsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::Ack>> PrepareAsyncSetInitialOdds(::grpc::ClientContext* context, const ::odds::SetInitialOddsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::Ack>>(PrepareAsyncSetInitialOddsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void UpdateMatchState(::grpc::ClientContext* context, const ::odds::MatchStateRequest* request, ::odds::OddsResponse* response, std::function<void(::grpc::Status)>) override;
      void UpdateMatchState(::grpc::ClientContext* context, const ::odds::MatchStateRequest* request, ::odds::OddsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void PlaceBet(::grpc::ClientContext* context, const ::odds::BetRequest* request, ::odds::OddsResponse* response, std::function<void(::grpc::Status)>) override;
      void PlaceBet(::grpc::ClientContext* context, const ::odds::BetRequest* request, ::odds::OddsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetOdds(::grpc::ClientContext* context, const ::odds::OddsQueryRequest* request, ::odds::OddsResponse* response, std::function<void(::grpc::Status)>) override;
      void GetOdds(::grpc::ClientContext* context, const ::odds::OddsQueryRequest* request, ::odds::OddsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SetInitialOdds(::grpc::ClientContext* context, const ::odds::SetInitialOddsRequest* request, ::odds::Ack* response, std::function<void(::grpc::Status)>) override;
      void SetInitialOdds(::grpc::ClientContext* context, const ::odds::SetInitialOddsRequest* request, ::odds::Ack* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>* AsyncUpdateMatchStateRaw(::grpc::ClientContext* context, const ::odds::MatchStateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>* PrepareAsyncUpdateMatchStateRaw(::grpc::ClientContext* context, const ::odds::MatchStateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>* AsyncPlaceBetRaw(::grpc::ClientContext* context, const ::odds::BetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>* PrepareAsyncPlaceBetRaw(::grpc::ClientContext* context, const ::odds::BetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>* AsyncGetOddsRaw(::grpc::ClientContext* context, const ::odds::OddsQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>* PrepareAsyncGetOddsRaw(::grpc::ClientContext* context, const ::odds::OddsQueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::odds::Ack>* AsyncSetInitialOddsRaw(::grpc::ClientContext* context, const ::odds::SetInitialOddsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::odds::Ack>* PrepareAsyncSetInitialOddsRaw(::grpc::ClientContext* context, const ::odds::SetInitialOddsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateMatchState_;
    const ::grpc::internal::RpcMethod rpcmethod_PlaceBet_;
    const ::grpc::internal::RpcMethod rpcmethod_GetOdds_;
    const ::grpc::internal::RpcMethod rpcmethod_SetInitialOdds_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Called by the manager to update match state for a specific game
    virtual ::grpc::Status UpdateMatchState(::grpc::ServerContext* context, const ::odds::MatchStateRequest* request, ::odds::OddsResponse* response);
    // Called when a user places a bet; updates exposure + recalculates odds
    virtual ::grpc::Status PlaceBet(::grpc::ServerContext* context, const ::odds::BetRequest* request, ::odds::OddsResponse* response);
    // Called to fetch latest odds for any market in any game
    virtual ::grpc::Status GetOdds(::grpc::ServerContext* context, const ::odds::OddsQueryRequest* request, ::odds::OddsResponse* response);
    virtual ::grpc::Status SetInitialOdds(::grpc::ServerContext* context, const ::odds::SetInitialOddsRequest* request, ::odds::Ack* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateMatchState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateMatchState() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_UpdateMatchState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMatchState(::grpc::ServerContext* /*context*/, const ::odds::MatchStateRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateMatchState(::grpc::ServerContext* context, ::odds::MatchStateRequest* request, ::grpc::ServerAsyncResponseWriter< ::odds::OddsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PlaceBet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PlaceBet() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PlaceBet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlaceBet(::grpc::ServerContext* /*context*/, const ::odds::BetRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPlaceBet(::grpc::ServerContext* context, ::odds::BetRequest* request, ::grpc::ServerAsyncResponseWriter< ::odds::OddsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetOdds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetOdds() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_GetOdds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOdds(::grpc::ServerContext* /*context*/, const ::odds::OddsQueryRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetOdds(::grpc::ServerContext* context, ::odds::OddsQueryRequest* request, ::grpc::ServerAsyncResponseWriter< ::odds::OddsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetInitialOdds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetInitialOdds() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_SetInitialOdds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetInitialOdds(::grpc::ServerContext* /*context*/, const ::odds::SetInitialOddsRequest* /*request*/, ::odds::Ack* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetInitialOdds(::grpc::ServerContext* context, ::odds::SetInitialOddsRequest* request, ::grpc::ServerAsyncResponseWriter< ::odds::Ack>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_UpdateMatchState<WithAsyncMethod_PlaceBet<WithAsyncMethod_GetOdds<WithAsyncMethod_SetInitialOdds<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_UpdateMatchState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateMatchState() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::odds::MatchStateRequest, ::odds::OddsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::odds::MatchStateRequest* request, ::odds::OddsResponse* response) { return this->UpdateMatchState(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateMatchState(
        ::grpc::MessageAllocator< ::odds::MatchStateRequest, ::odds::OddsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::odds::MatchStateRequest, ::odds::OddsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateMatchState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMatchState(::grpc::ServerContext* /*context*/, const ::odds::MatchStateRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateMatchState(
      ::grpc::CallbackServerContext* /*context*/, const ::odds::MatchStateRequest* /*request*/, ::odds::OddsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_PlaceBet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PlaceBet() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::odds::BetRequest, ::odds::OddsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::odds::BetRequest* request, ::odds::OddsResponse* response) { return this->PlaceBet(context, request, response); }));}
    void SetMessageAllocatorFor_PlaceBet(
        ::grpc::MessageAllocator< ::odds::BetRequest, ::odds::OddsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::odds::BetRequest, ::odds::OddsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PlaceBet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlaceBet(::grpc::ServerContext* /*context*/, const ::odds::BetRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PlaceBet(
      ::grpc::CallbackServerContext* /*context*/, const ::odds::BetRequest* /*request*/, ::odds::OddsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetOdds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetOdds() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::odds::OddsQueryRequest, ::odds::OddsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::odds::OddsQueryRequest* request, ::odds::OddsResponse* response) { return this->GetOdds(context, request, response); }));}
    void SetMessageAllocatorFor_GetOdds(
        ::grpc::MessageAllocator< ::odds::OddsQueryRequest, ::odds::OddsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::odds::OddsQueryRequest, ::odds::OddsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetOdds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOdds(::grpc::ServerContext* /*context*/, const ::odds::OddsQueryRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetOdds(
      ::grpc::CallbackServerContext* /*context*/, const ::odds::OddsQueryRequest* /*request*/, ::odds::OddsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetInitialOdds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetInitialOdds() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::odds::SetInitialOddsRequest, ::odds::Ack>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::odds::SetInitialOddsRequest* request, ::odds::Ack* response) { return this->SetInitialOdds(context, request, response); }));}
    void SetMessageAllocatorFor_SetInitialOdds(
        ::grpc::MessageAllocator< ::odds::SetInitialOddsRequest, ::odds::Ack>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::odds::SetInitialOddsRequest, ::odds::Ack>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetInitialOdds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetInitialOdds(::grpc::ServerContext* /*context*/, const ::odds::SetInitialOddsRequest* /*request*/, ::odds::Ack* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetInitialOdds(
      ::grpc::CallbackServerContext* /*context*/, const ::odds::SetInitialOddsRequest* /*request*/, ::odds::Ack* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_UpdateMatchState<WithCallbackMethod_PlaceBet<WithCallbackMethod_GetOdds<WithCallbackMethod_SetInitialOdds<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_UpdateMatchState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateMatchState() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_UpdateMatchState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMatchState(::grpc::ServerContext* /*context*/, const ::odds::MatchStateRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PlaceBet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PlaceBet() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PlaceBet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlaceBet(::grpc::ServerContext* /*context*/, const ::odds::BetRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetOdds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetOdds() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_GetOdds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOdds(::grpc::ServerContext* /*context*/, const ::odds::OddsQueryRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetInitialOdds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetInitialOdds() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_SetInitialOdds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetInitialOdds(::grpc::ServerContext* /*context*/, const ::odds::SetInitialOddsRequest* /*request*/, ::odds::Ack* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateMatchState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateMatchState() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_UpdateMatchState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMatchState(::grpc::ServerContext* /*context*/, const ::odds::MatchStateRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateMatchState(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PlaceBet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PlaceBet() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PlaceBet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlaceBet(::grpc::ServerContext* /*context*/, const ::odds::BetRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPlaceBet(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetOdds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetOdds() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_GetOdds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOdds(::grpc::ServerContext* /*context*/, const ::odds::OddsQueryRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetOdds(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetInitialOdds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetInitialOdds() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_SetInitialOdds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetInitialOdds(::grpc::ServerContext* /*context*/, const ::odds::SetInitialOddsRequest* /*request*/, ::odds::Ack* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetInitialOdds(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateMatchState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateMatchState() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateMatchState(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateMatchState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMatchState(::grpc::ServerContext* /*context*/, const ::odds::MatchStateRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateMatchState(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PlaceBet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PlaceBet() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PlaceBet(context, request, response); }));
    }
    ~WithRawCallbackMethod_PlaceBet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlaceBet(::grpc::ServerContext* /*context*/, const ::odds::BetRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PlaceBet(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetOdds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetOdds() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetOdds(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetOdds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetOdds(::grpc::ServerContext* /*context*/, const ::odds::OddsQueryRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetOdds(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetInitialOdds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetInitialOdds() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetInitialOdds(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetInitialOdds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetInitialOdds(::grpc::ServerContext* /*context*/, const ::odds::SetInitialOddsRequest* /*request*/, ::odds::Ack* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetInitialOdds(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateMatchState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateMatchState() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::odds::MatchStateRequest, ::odds::OddsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::odds::MatchStateRequest, ::odds::OddsResponse>* streamer) {
                       return this->StreamedUpdateMatchState(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateMatchState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateMatchState(::grpc::ServerContext* /*context*/, const ::odds::MatchStateRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateMatchState(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::odds::MatchStateRequest,::odds::OddsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PlaceBet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PlaceBet() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::odds::BetRequest, ::odds::OddsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::odds::BetRequest, ::odds::OddsResponse>* streamer) {
                       return this->StreamedPlaceBet(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PlaceBet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PlaceBet(::grpc::ServerContext* /*context*/, const ::odds::BetRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPlaceBet(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::odds::BetRequest,::odds::OddsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetOdds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetOdds() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::odds::OddsQueryRequest, ::odds::OddsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::odds::OddsQueryRequest, ::odds::OddsResponse>* streamer) {
                       return this->StreamedGetOdds(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetOdds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetOdds(::grpc::ServerContext* /*context*/, const ::odds::OddsQueryRequest* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetOdds(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::odds::OddsQueryRequest,::odds::OddsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetInitialOdds : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetInitialOdds() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::odds::SetInitialOddsRequest, ::odds::Ack>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::odds::SetInitialOddsRequest, ::odds::Ack>* streamer) {
                       return this->StreamedSetInitialOdds(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetInitialOdds() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetInitialOdds(::grpc::ServerContext* /*context*/, const ::odds::SetInitialOddsRequest* /*request*/, ::odds::Ack* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetInitialOdds(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::odds::SetInitialOddsRequest,::odds::Ack>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_UpdateMatchState<WithStreamedUnaryMethod_PlaceBet<WithStreamedUnaryMethod_GetOdds<WithStreamedUnaryMethod_SetInitialOdds<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_UpdateMatchState<WithStreamedUnaryMethod_PlaceBet<WithStreamedUnaryMethod_GetOdds<WithStreamedUnaryMethod_SetInitialOdds<Service > > > > StreamedService;
};

}  // namespace odds


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_odds_5fengine_2eproto__INCLUDED
