// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: odds_engine.proto
#ifndef GRPC_odds_5fengine_2eproto__INCLUDED
#define GRPC_odds_5fengine_2eproto__INCLUDED

#include "odds_engine.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace odds {

class OddsEngine final {
 public:
  static constexpr char const* service_full_name() {
    return "odds.OddsEngine";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status UpdateMatchState(::grpc::ClientContext* context, const ::odds::BallUpdate& request, ::odds::OddsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>> AsyncUpdateMatchState(::grpc::ClientContext* context, const ::odds::BallUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>>(AsyncUpdateMatchStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>> PrepareAsyncUpdateMatchState(::grpc::ClientContext* context, const ::odds::BallUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>>(PrepareAsyncUpdateMatchStateRaw(context, request, cq));
    }
    virtual ::grpc::Status PlacedBet(::grpc::ClientContext* context, const ::odds::Bet& request, ::odds::OddsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>> AsyncPlacedBet(::grpc::ClientContext* context, const ::odds::Bet& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>>(AsyncPlacedBetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>> PrepareAsyncPlacedBet(::grpc::ClientContext* context, const ::odds::Bet& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>>(PrepareAsyncPlacedBetRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void UpdateMatchState(::grpc::ClientContext* context, const ::odds::BallUpdate* request, ::odds::OddsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UpdateMatchState(::grpc::ClientContext* context, const ::odds::BallUpdate* request, ::odds::OddsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void PlacedBet(::grpc::ClientContext* context, const ::odds::Bet* request, ::odds::OddsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PlacedBet(::grpc::ClientContext* context, const ::odds::Bet* request, ::odds::OddsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>* AsyncUpdateMatchStateRaw(::grpc::ClientContext* context, const ::odds::BallUpdate& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>* PrepareAsyncUpdateMatchStateRaw(::grpc::ClientContext* context, const ::odds::BallUpdate& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>* AsyncPlacedBetRaw(::grpc::ClientContext* context, const ::odds::Bet& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::odds::OddsResponse>* PrepareAsyncPlacedBetRaw(::grpc::ClientContext* context, const ::odds::Bet& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status UpdateMatchState(::grpc::ClientContext* context, const ::odds::BallUpdate& request, ::odds::OddsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>> AsyncUpdateMatchState(::grpc::ClientContext* context, const ::odds::BallUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>>(AsyncUpdateMatchStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>> PrepareAsyncUpdateMatchState(::grpc::ClientContext* context, const ::odds::BallUpdate& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>>(PrepareAsyncUpdateMatchStateRaw(context, request, cq));
    }
    ::grpc::Status PlacedBet(::grpc::ClientContext* context, const ::odds::Bet& request, ::odds::OddsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>> AsyncPlacedBet(::grpc::ClientContext* context, const ::odds::Bet& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>>(AsyncPlacedBetRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>> PrepareAsyncPlacedBet(::grpc::ClientContext* context, const ::odds::Bet& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>>(PrepareAsyncPlacedBetRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void UpdateMatchState(::grpc::ClientContext* context, const ::odds::BallUpdate* request, ::odds::OddsResponse* response, std::function<void(::grpc::Status)>) override;
      void UpdateMatchState(::grpc::ClientContext* context, const ::odds::BallUpdate* request, ::odds::OddsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void PlacedBet(::grpc::ClientContext* context, const ::odds::Bet* request, ::odds::OddsResponse* response, std::function<void(::grpc::Status)>) override;
      void PlacedBet(::grpc::ClientContext* context, const ::odds::Bet* request, ::odds::OddsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>* AsyncUpdateMatchStateRaw(::grpc::ClientContext* context, const ::odds::BallUpdate& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>* PrepareAsyncUpdateMatchStateRaw(::grpc::ClientContext* context, const ::odds::BallUpdate& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>* AsyncPlacedBetRaw(::grpc::ClientContext* context, const ::odds::Bet& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::odds::OddsResponse>* PrepareAsyncPlacedBetRaw(::grpc::ClientContext* context, const ::odds::Bet& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_UpdateMatchState_;
    const ::grpc::internal::RpcMethod rpcmethod_PlacedBet_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status UpdateMatchState(::grpc::ServerContext* context, const ::odds::BallUpdate* request, ::odds::OddsResponse* response);
    virtual ::grpc::Status PlacedBet(::grpc::ServerContext* context, const ::odds::Bet* request, ::odds::OddsResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_UpdateMatchState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UpdateMatchState() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_UpdateMatchState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMatchState(::grpc::ServerContext* /*context*/, const ::odds::BallUpdate* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateMatchState(::grpc::ServerContext* context, ::odds::BallUpdate* request, ::grpc::ServerAsyncResponseWriter< ::odds::OddsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_PlacedBet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PlacedBet() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_PlacedBet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlacedBet(::grpc::ServerContext* /*context*/, const ::odds::Bet* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPlacedBet(::grpc::ServerContext* context, ::odds::Bet* request, ::grpc::ServerAsyncResponseWriter< ::odds::OddsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_UpdateMatchState<WithAsyncMethod_PlacedBet<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_UpdateMatchState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UpdateMatchState() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::odds::BallUpdate, ::odds::OddsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::odds::BallUpdate* request, ::odds::OddsResponse* response) { return this->UpdateMatchState(context, request, response); }));}
    void SetMessageAllocatorFor_UpdateMatchState(
        ::grpc::MessageAllocator< ::odds::BallUpdate, ::odds::OddsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::odds::BallUpdate, ::odds::OddsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UpdateMatchState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMatchState(::grpc::ServerContext* /*context*/, const ::odds::BallUpdate* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateMatchState(
      ::grpc::CallbackServerContext* /*context*/, const ::odds::BallUpdate* /*request*/, ::odds::OddsResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_PlacedBet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PlacedBet() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::odds::Bet, ::odds::OddsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::odds::Bet* request, ::odds::OddsResponse* response) { return this->PlacedBet(context, request, response); }));}
    void SetMessageAllocatorFor_PlacedBet(
        ::grpc::MessageAllocator< ::odds::Bet, ::odds::OddsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::odds::Bet, ::odds::OddsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PlacedBet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlacedBet(::grpc::ServerContext* /*context*/, const ::odds::Bet* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PlacedBet(
      ::grpc::CallbackServerContext* /*context*/, const ::odds::Bet* /*request*/, ::odds::OddsResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_UpdateMatchState<WithCallbackMethod_PlacedBet<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_UpdateMatchState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UpdateMatchState() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_UpdateMatchState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMatchState(::grpc::ServerContext* /*context*/, const ::odds::BallUpdate* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_PlacedBet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PlacedBet() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_PlacedBet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlacedBet(::grpc::ServerContext* /*context*/, const ::odds::Bet* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_UpdateMatchState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UpdateMatchState() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_UpdateMatchState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMatchState(::grpc::ServerContext* /*context*/, const ::odds::BallUpdate* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUpdateMatchState(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_PlacedBet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PlacedBet() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_PlacedBet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlacedBet(::grpc::ServerContext* /*context*/, const ::odds::Bet* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPlacedBet(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UpdateMatchState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UpdateMatchState() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UpdateMatchState(context, request, response); }));
    }
    ~WithRawCallbackMethod_UpdateMatchState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UpdateMatchState(::grpc::ServerContext* /*context*/, const ::odds::BallUpdate* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UpdateMatchState(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PlacedBet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PlacedBet() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PlacedBet(context, request, response); }));
    }
    ~WithRawCallbackMethod_PlacedBet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PlacedBet(::grpc::ServerContext* /*context*/, const ::odds::Bet* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PlacedBet(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UpdateMatchState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UpdateMatchState() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::odds::BallUpdate, ::odds::OddsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::odds::BallUpdate, ::odds::OddsResponse>* streamer) {
                       return this->StreamedUpdateMatchState(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UpdateMatchState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UpdateMatchState(::grpc::ServerContext* /*context*/, const ::odds::BallUpdate* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUpdateMatchState(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::odds::BallUpdate,::odds::OddsResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PlacedBet : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PlacedBet() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::odds::Bet, ::odds::OddsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::odds::Bet, ::odds::OddsResponse>* streamer) {
                       return this->StreamedPlacedBet(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PlacedBet() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PlacedBet(::grpc::ServerContext* /*context*/, const ::odds::Bet* /*request*/, ::odds::OddsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPlacedBet(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::odds::Bet,::odds::OddsResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_UpdateMatchState<WithStreamedUnaryMethod_PlacedBet<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_UpdateMatchState<WithStreamedUnaryMethod_PlacedBet<Service > > StreamedService;
};

}  // namespace odds


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_odds_5fengine_2eproto__INCLUDED
